AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
      
  EnvType:
    Description: Environmet type.
    Default: test
    Type: String
    AllowedValues:
      - prod
      - test
    ConstraintDescription: must specify prod or test.

Conditions:
  # 開発環境ごとにリソースの内容を切り分ける
  # EnvTypeがprodとイコールなら
  CreateProdResources: !Equals [ !Ref EnvType, prod]
  # CreateProdResources: !Equals
  #   - !Ref EnvType
  #   - prod

Resources:
  # インスタンスは環境によってリソース内容が変わらない設定
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: t2.micro

  MountPoint:
    Type: AWS::EC2::VolumeAttachment
    Condition: CreateProdResources
    Properties:
      InstanceId: !Ref EC2Instance
      VolumeId: !Ref NewVolume
      Device: /dev/sdh

  NewVolume:
    Type: AWS::EC2::Volume
    Condition: CreateProdResources
    Properties:
      Size: 1
      AvailabilityZone:
        # 属性の取得->リソースからAZを
        # なんのためにAZの情報を取得しなければならないのか?
        !GetAtt EC2Instance.AvailabilityZone
      # AvailabilityZone: !GetAtt
      #   - EC2Instaance
      #   - AvailabilityZone

Outputs:
  VolumeId:
    Condition: CreateProdResources
    Value: !Ref NewVolume
